# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Solidity testing CI

on:
  # push:
  #   branches: [ dev ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  truffle-test:
    name: truffle-test
    # defaults:
    #   run:
    #     working-directory: SOLIDITY
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 #only brings last commit
      - name: Use Node.js ${{ matrix.node-version }}      
        uses: actions/setup-node@v3      
        with:
          node-version: ${{ matrix.node-version }}
          #cache: 'npm'          
      - name: Install truffle
        run: npm install -g truffle@5.11.0 --no-audit --no-fund --no-optional
      
      - name: Install ganache
        run: npm install -g ganache@7.9.0 --no-audit --no-fund --no-optional

      - name: Install local libraries
        run: npm install --no-audit --no-fund --no-optional

      - name: Run linter checks        
        run: npm run linter

      - name: Compile contracts      
        run: npm run compile 

      - name: Run ganache fork on background
        run: npm run ganacheFork &

      - name: Run truffle test
        run: npm run test 